[build]
  publish = "public" # Indique à Netlify de chercher les fichiers dans le dossier "public"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*#invite_token=:token"
  to = "/admin/"
  status = 200
