backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads" # Où stocker les images
public_folder: "/uploads"      # Chemin public pour les afficher

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "body", label: "Contenu", widget: "markdown" }

  - name: "blog"
    label: "Articles de Blog"
    folder: "content/blog"
    create: true
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Contenu", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image", required: false }

  - name: "events"
    label: "Événements"
    folder: "content/events"
    create: true
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Affiche de l'Événement", widget: "image", required: false }
